---
operator:
  operator:
    env:
      - name: OPERATOR_STS_ENABLED
        value: "on"
      - name: WATCHED_NAMESPACE   # This must match exactly with each tenant namespace, otherwise, the tenant will not be deployed by minio operator
        value: "minio-tenant-mkpl,minio-tenant-svcseg,minio-tenant-tlbx"

    image:
      repository: quay.io/minio/operator
      tag: v7.1.1
      pullPolicy: IfNotPresent

    replicaCount: 2

    nodeSelector: 
      directpv-node: "yes"
    
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - minio-operator
            topologyKey: "kubernetes.io/hostname"

    tolerations:
      - key: minio-directpv
        value: storage
        effect: NoSchedule

    resources:
      requests:
        cpu: 2
        memory: 4Gi
        ephemeral-storage: 5Gi
      limits:
        cpu: 4
        memory: 8Gi
