###
# Root key for Operator Helm Chart
operator:
  replicaCount: 3
  image:
    repository: minio/operator
    tag: v7.1.0
    pullPolicy: IfNotPresent
  #SecurityContext:
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  #Resources:
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
      ephemeral-storage: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 1Gi