apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../v4.0/base/
  - ../cronjobs/

patches:
  - path: deployment-affinity-selector-patch.yaml
    target:
      kind: Deployment
      name: controller
  - path: daemonset-node-toleration-patch.yaml
    target:
      kind: DaemonSet
      name: node-server
