apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: minio-config-external-secret
 namespace: {{ .Release.Namespace }}
spec:
 secretStoreRef:
   name: {{ .Values.eso.secret_store.name }}
   kind: {{ .Values.eso.store_kind | default "ClusterSecretStore" }}
 target:
   name: minio-config-secret
   template:
     engineVersion: v2
     data:
       config.env: |
         export MINIO_ROOT_USER="{{ `{{ .user }}` }}"
         export MINIO_ROOT_PASSWORD="{{ `{{ .password }}` }}"
         export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM="{{ `{{ .secret }}` }}"
 data:
   - secretKey: user
     remoteRef:
       key: {{ .Values.eso.minio.config_secret_path }}
       property: {{ .Values.eso.minio.user_secret_property }}
   - secretKey: password
     remoteRef:
       key: {{ .Values.eso.minio.config_secret_path }}
       property: {{ .Values.eso.minio.password_secret_property }}
   - secretKey: secret
     remoteRef:
       key: {{ .Values.eso.minio.config_secret_path }}
       property: {{ .Values.eso.minio.client_secret_property }}
