apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller 
spec:
  template:
    spec:
      nodeSelector:
        directpv-controller: "yes"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: selector.directpv.min.io
                    operator: In
                    values:
                      - controller-controller
              topologyKey: "kubernetes.io/hostname"
