{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  # ... other operator config
{{- end }}
