apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../cronjobs

images:
  - name: quay.io/minio/directpv
    digest: sha256:352806476d3962a6fc4b8a615c95ce2391ca8b0ece00c99b402fd140555b69b5
  - name: directpv-discovery
    newName: gitlab.acme.com:5050/acme-marketplace/marketplace/integration-level/registry-dev/directpv-tool
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.1.5
    target:
      kind: Deployment
      name: controller
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.1.5
    target:
      kind: DaemonSet
      name: node-server
  - path: deployment-affinity-selector-patch.yaml
    target:
      kind: Deployment
      name: controller
  - path: daemonset-node-toleration-patch.yaml
    target:
      kind: DaemonSet
      name: node-server
  - patch: |-
      - op: add
        path: /metadata/labels/marketplace-injection-cred
        value: 'True'
    target:
      kind: Namespace
      name: directpv
