{{- if .Values.sts.enabled }}
{{- range $roleName, $roleConfig := .Values.policies }}
{{- if and $roleConfig.enabled $roleConfig.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant.serviceAccountName" (dict "serviceAccount" $roleConfig.serviceAccount "roleName" $roleName "root" $) }}
  namespace: {{ .Values.tenant.namespace }}
  labels:
    {{- include "tenant.serviceAccountLabels" $ | nindent 4 }}
    app.kubernetes.io/role: {{ $roleName }}
    {{- with $roleConfig.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $roleConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
{{- end }}