apiVersion: v2
appVersion: v7.1.1
description: A Helm chart for MinIO Operator
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: tenant-beta
sources:
- https://github.com/minio/operator
type: application
version: 7.1.1